server:
  port: 8087
spring:
  datasource:
    name: training
    url: jdbc:postgresql://127.0.0.1:5432/test
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    dbcp2:
      initial-size: 10
      max-idle: 15
      min-idle: 5
      max-wait-millis: 10000
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false
  servlet.multipart.max-file-size: 20MB
  servlet.multipart.max-request-size: 20MB


